config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: :create
    resources :reviews, only: :create
  end

  resources :doses, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    has_many :reviews, dependent: :destroy

    validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    has_many :cocktails, through: :doses

    validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

    def index
        @cocktails = Cocktail.all
    end

    def show
        @cocktail = Cocktail.find(params[:id])
        @dose = Dose.new
        @review = Review.new
    end

    def new
        @cocktail = Cocktail.new
    end

    def create
        @cocktail = Cocktail.new(cocktail_params)
        if @cocktail.save
            redirect_to cocktail_path(@cocktail)
        else
            render :new
        end
    end

    private

    def cocktail_params
        params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    before_action :find_cocktail, only: %i[new create]

    def new
        @dose = Dose.new
    end

    def create
        @dose = Dose.new(dose_params)
        @dose.cocktail = @cocktail

        if @dose.save
            redirect_to cocktail_path(@cocktail)
        else
            render :new
        end
    end

    def destroy
        @dose = Dose.find(params[:id])
        @dose.destroy

        redirect_to cocktail_path(@dose.cocktail)
    end

    private

    def dose_params
        params.require(:dose).permit(:description, :ingredient_id)
    end

    def find_cocktail
        @cocktail = Cocktail.find(params[:cocktail_id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_cocktail, only: %i[new create]

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.cocktail = @cocktail

        if @review.save
            redirect_to cocktail_path(@cocktail)
        else
            render :new
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy

        redirect_to cocktail_path(@review.cocktail)
    end

    private 

    def review_params
        params.require(:review).permit(:content)
    end

    def find_cocktail
        @cocktail = Cocktail.find(params[:cocktail_id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
    <%= link_to 'Create your Cocktail', new_cocktail_path, class: 'btn btn-outline-warning' %>

    <div class="row">
        <% @cocktails.each do |cocktail| %>
                <div class="col-sm-6 col-md-4 col-3">
                    <div class="card text-white bg-dark m-5">
                        <img src="https://source.unsplash.com/1600x900/?cocktail" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title"><%= cocktail.name %></h5>
                            <%= link_to 'Recipe', cocktail_path(cocktail), class: 'btn btn-outline-warning' %>
                        </div>
                    </div>
                </div>
        <% end %>
    </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
    <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.submit 'Create Cocktail', class: 'btn btn-outline-warning' %>
    <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
    <h1><%= @cocktail.name %></h1>
    <hr>
    <div class="row">
        <div class="col-sm-6">
            <h2>This cocktail contains:</h2>
            <% if @cocktail.doses.empty? %>
                <p>Nothing yet :(</p>
            <% else %>
                <ul>
                    <% @cocktail.doses.each do |dose| %>
                        <li><%= dose.ingredient.name %> - <%= dose.description %></li>
                        <ul><li><%= link_to 'Delete ingredient', dose_path(dose), method: :delete %></li></ul>
                    <% end %>
                </ul>
            <% end %>
        </div>
        <div class="col-sm-6">
            <h2>Add a new ingredient</h2>
            <%= simple_form_for [@cocktail, @dose] do |f| %>
                <%= f.association :ingredient, input_html: { class: 'select2' } %>
                <%= f.input :description %>
                <%= f.submit 'Add Ingredient' %>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h2>Leave a review!</h2>
            <%= simple_form_for [@cocktail, @review] do |f| %>
                <%= f.input :content %>
                <%= f.submit 'Add Review!' %>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <% if @cocktail.reviews.empty? %>
                <p>No reviews yet :(</p>
            <% else %>
                <% @cocktail.reviews.each do |review| %>
                    <h4><%= review.content %></h4>
                    <p><%= link_to 'Delete Review', review_path(review), method: :delete %></p>
                    <hr>
                <% end %>      
            <% end %>
        </div>
    </div>



    <%= link_to 'All Cocktails', cocktails_path, class: 'btn btn-outline-warning' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisterCocktailReboot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>